### ISSUE TITLE
Navbar items are outside <nav>  tag

### ISSUE THREAD

**Issue by angeluray** [limavfabio/My-Portfolio#5]
You've done a great job! 💯 I think it would be better if all items belonging to the `<navbar>`
 were inside the `<nav>` tag kindly consider fixing it🤓.

**Comment by belmeetmule** [comment]
To be more specific, the hubergur button at line 24 of your index.html file should be inside a `<navbar>` tag.

**Comment by limavfabio** [comment]
All right, thank you for bringing this to my attention, I'll fix it on the next PR

**Comment by AlucardSanin** [comment]
Such a great feature to add, well done. Remember to work with the proper HTML semantics while coding. 

Some tags belong to certain sections of the page.
